// <auto-generated />
using ApiTestBK.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTestBK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250816180601_Primera migracion")]
    partial class Primeramigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTestBK.Models.Entities.ComprobanteFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContribuyenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NCF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContribuyenteId");

                    b.ToTable("ComprobantesFiscales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContribuyenteId = 1,
                            Itbis18 = 36.00m,
                            Monto = 200.00m,
                            NCF = "E310000000001",
                            RncCedula = "00112345678"
                        },
                        new
                        {
                            Id = 2,
                            ContribuyenteId = 1,
                            Itbis18 = 270.00m,
                            Monto = 1500.00m,
                            NCF = "E310000000002",
                            RncCedula = "00112345678"
                        },
                        new
                        {
                            Id = 3,
                            ContribuyenteId = 2,
                            Itbis18 = 90.00m,
                            Monto = 500.00m,
                            NCF = "E310000000003",
                            RncCedula = "00187654321"
                        },
                        new
                        {
                            Id = 4,
                            ContribuyenteId = 3,
                            Itbis18 = 1800.00m,
                            Monto = 10000.00m,
                            NCF = "B010000000001",
                            RncCedula = "13145678901"
                        },
                        new
                        {
                            Id = 5,
                            ContribuyenteId = 3,
                            Itbis18 = 1350.00m,
                            Monto = 7500.00m,
                            NCF = "B010000000002",
                            RncCedula = "13145678901"
                        },
                        new
                        {
                            Id = 6,
                            ContribuyenteId = 3,
                            Itbis18 = 450.00m,
                            Monto = 2500.00m,
                            NCF = "B010000000003",
                            RncCedula = "13145678901"
                        },
                        new
                        {
                            Id = 7,
                            ContribuyenteId = 5,
                            Itbis18 = 216.00m,
                            Monto = 1200.00m,
                            NCF = "E310000000004",
                            RncCedula = "40199887766"
                        },
                        new
                        {
                            Id = 8,
                            ContribuyenteId = 5,
                            Itbis18 = 54.00m,
                            Monto = 300.00m,
                            NCF = "E310000000005",
                            RncCedula = "40199887766"
                        });
                });

            modelBuilder.Entity("ApiTestBK.Models.Entities.Contribuyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contribuyentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estatus = "activo",
                            Nombre = "JUAN PEREZ",
                            RncCedula = "00112345678",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            Id = 2,
                            Estatus = "activo",
                            Nombre = "MARIA LOPEZ",
                            RncCedula = "00187654321",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            Id = 3,
                            Estatus = "inactivo",
                            Nombre = "EMPRESAS DOMINICANAS SRL",
                            RncCedula = "13145678901",
                            Tipo = "PERSONA JURIDICA"
                        },
                        new
                        {
                            Id = 4,
                            Estatus = "suspendido",
                            Nombre = "PEDRO GARCIA",
                            RncCedula = "40211222333",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            Id = 5,
                            Estatus = "activo",
                            Nombre = "SOLUCIONES TECNICAS EIRL",
                            RncCedula = "40199887766",
                            Tipo = "PERSONA JURIDICA"
                        });
                });

            modelBuilder.Entity("ApiTestBK.Models.Entities.ComprobanteFiscal", b =>
                {
                    b.HasOne("ApiTestBK.Models.Entities.Contribuyente", "Contribuyente")
                        .WithMany("ComprobantesFiscales")
                        .HasForeignKey("ContribuyenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("ApiTestBK.Models.Entities.Contribuyente", b =>
                {
                    b.Navigation("ComprobantesFiscales");
                });
#pragma warning restore 612, 618
        }
    }
}
